name: Run Unit Tests for Personium core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: cat settings.xml
      run: cat ~/.m2/settings.xml
    - name: Build with Maven
      run: mvn -B clean test --file pom.xml
