name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER: personiumio
      GITHUB_TOKEN: ${{ secrets.PERSONIUM_GITHUB_TOKEN }}

    steps:
    - name: Get Component Name
      run: |
        echo "COMPONENT=$(echo $GITHUB_REPOSITORY | awk -F '/' '{ print $2 }')" >> $GITHUB_ENV

    - name: Get Release Version String
      run: |
        echo "RELEASE_VERSION=$(cat CHANGELOG.md | grep -m 1 -E '## .+' | awk '{ print $2 }')" >> $GITHUB_ENV

    - name: Debug Env value
      run: |
        env

    - name: git settings
      run: |
        git config --global user.name "Personium Bot"
        git config --global user.email "personium.io@gmail.com"
        git clone https://github.com/${GITHUB_REPOSITORY}.git .
        git checkout master


    - name: Remove -SNAPSHOT from pom.xml on master branch
      run: |
        bash ./.github/workflows/scripts/remove-SNAPSHOT.sh

    - name: Create Release Note
      run: |
        python3 ./.github/workflows/scripts/create-release-note.py

    - name: Update versions on develop branch
      run: |
        bash ./.github/workflows/scripts/update-version.sh
