name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_USER: personiumio
      GITHUB_TOKEN: ${{ secrets.PERSONIUM_GITHUB_TOKEN }}
      COMPONENT: personium-core

    steps:
    - name: git settings
      run: |
        git config --global user.name "Personium Bot"
        git config --global user.email "personium.io@gmail.com"

    - name: Remove -SNAPSHOT from pom.xml on master branch
      run: |
        bash ./.github/workflows/scripts/remove-SNAPSHOT.sh

    - name: Create Release Note
      run: |
        python3 ./.github/workflows/scripts/create-release-note.py

    - name: Update versions on develop branch
      run: |
        bash ./.github/workflows/scripts/update-version.sh
